export const INSERT_STRING = "INSERT_STRING";
export const DELETE_STRING = "DELETE_STRING";
export const UPLOAD_PHOTO = "UPLOAD_PHOTO";
export const ALERT_APPLICANT = "ALERT_APPLICANT";
export const START_TIMER = "START_TIMER";
export const END_TIMER = "END_TIMER";
